// Requires Playwright and Chrome. Run against `python -m tests.ui_server` only.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const { mkdir } = require('node:fs/promises');

(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const base = 'http://127.0.0.1:8011';
  const headers = { Authorization: 'Bearer browser-test-token-000000000000000000' };
  const output = process.env.UI_TEST_OUTPUT || '/tmp/assistant-ui-validation';
  await mkdir(output, { recursive: true });
  async function connect() {
    await page.locator('.connection-panel').evaluate(el => el.open = true);
    await page.locator('#token').fill('browser-test-token-000000000000000000');
    await page.locator('#connection button[type=submit]').click();
    await page.waitForFunction(() => document.getElementById('notice').textContent.startsWith('Connected.'));
  }
  try {
    const identity = await (await page.request.get(`${base}/assistant`, { headers })).json();
    assert.equal(identity.user_id, 'f367bf59-431a-44ea-839e-371dbf4a26f9', 'Use only the synthetic fixture server');
    for (const note of await (await page.request.get(`${base}/memories`, { headers })).json()) await page.request.delete(`${base}/memories/${note.id}`, { headers });
    await page.request.put(`${base}/assistant/theme`, { headers, data: {} });
    await page.goto(`${base}/ui/`);
    await connect();
    await page.locator('#settings-open').click();
    await page.locator('#theme').selectOption('dark');
    assert.equal(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--background').trim()), '#f4f6fa');
    await page.locator('#theme-apply').click();
    await page.waitForFunction(() => document.getElementById('theme-status').textContent === 'Appearance saved.');
    assert.equal(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--background').trim()), '#141925');
    await page.reload(); await connect();
    assert.equal(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--background').trim()), '#141925');
    await page.locator('#settings-open').click();
    await page.locator('#theme-prompt').fill('A cozy reading room');
    await page.locator('#theme-generate').click();
    await page.waitForFunction(() => document.getElementById('theme-status').textContent.startsWith('Preview ready.'));
    assert.equal(await page.locator('#theme-preview').evaluate(el => getComputedStyle(el).getPropertyValue('--background').trim()), '#f4efe5');
    await page.locator('#theme-apply').click();
    await page.waitForFunction(() => document.getElementById('theme-status').textContent === 'Appearance saved.');
    await page.locator('#theme-prompt').fill('invalid');
    await page.locator('#theme-generate').click();
    await page.waitForFunction(() => document.getElementById('theme-status').textContent.includes('502'));
    assert.equal(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--background').trim()), '#f4efe5');
    await page.locator('#preset').selectOption('concise');
    await page.locator('#save').click();
    await page.waitForFunction(() => document.getElementById('tone-status').textContent === 'Communication settings saved.');
    assert.equal((await (await page.request.get(`${base}/assistant`, { headers })).json()).verbosity, .2);
    await page.locator('#tone-live').click();
    await page.waitForFunction(() => document.getElementById('tone-status').textContent.startsWith('Live model sample.'));
    await page.locator('#memory-content').fill('My project is Cedar.');
    await page.locator('#memory-save').click();
    await page.waitForFunction(() => document.getElementById('memory-count').textContent === '1 of 20 notes');
    await page.locator('[data-memory-action=edit]').click();
    await page.locator('#memory-content').fill('My project is Birch.');
    await page.locator('#memory-save').click();
    await page.waitForFunction(() => document.querySelector('.note p')?.textContent === 'My project is Birch.');
    await page.locator('#settings-close').click();
    await page.locator('#new').click();
    await page.waitForFunction(() => !document.getElementById('send').disabled);
    await page.locator('#content').fill('I enjoy clear explanations.');
    await page.locator('#send').click();
    await page.waitForFunction(() => !document.getElementById('send').disabled && document.querySelector('.message.assistant small')?.textContent === 'completed');
    await page.locator('[data-memory-action=remember]').click();
    assert.equal(await page.locator('#memory-count').textContent(), '1 of 20 notes');
    assert.equal(await page.locator('#memory-content').inputValue(), 'I enjoy clear explanations.');
    await page.locator('#memory-save').click();
    await page.waitForFunction(() => document.getElementById('memory-count').textContent === '2 of 20 notes');
    await page.locator('[data-memory-action=delete]').first().click();
    await page.waitForFunction(() => document.getElementById('memory-count').textContent === '1 of 20 notes');
    await page.locator('#theme-reset').click();
    await page.waitForFunction(() => document.getElementById('theme-status').textContent === 'Default appearance restored.');
    await page.locator('#settings-dialog').evaluate(el => el.scrollTop = 0);
    await page.screenshot({ path: `${output}/settings-desktop.png`, fullPage: true });
    await page.locator('#settings-close').click();
    await page.locator('#shorter').click();
    assert.equal(await page.locator('#content').inputValue(), 'Please make your last answer shorter.');
    await page.locator('#content').fill('slow response please');
    await page.locator('#send').click();
    await page.waitForFunction(() => document.querySelectorAll('.message.assistant').length === 2 && document.querySelectorAll('.message.assistant')[1].textContent.includes('Thinking'));
    await page.locator('#stop').click();
    await page.waitForFunction(() => !document.getElementById('send').disabled && document.querySelectorAll('.message.assistant small')[1].textContent === 'cancelled');
    await page.screenshot({ path: `${output}/chat-desktop.png`, fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.locator('#settings-open').click();
    assert(await page.locator('#settings-dialog').evaluate(el => el.scrollWidth <= el.clientWidth));
    await page.locator('#memory-content').focus();
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#settings-dialog').evaluate(el => el.open), false);
    await page.screenshot({ path: `${output}/chat-mobile.png`, fullPage: true });
    await page.evaluate(() => document.documentElement.style.fontSize = '32px');
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'No horizontal overflow at 200% text size');
    await page.locator('#settings-open').click();
    assert(await page.locator('#settings-dialog').evaluate(el => el.scrollWidth <= el.clientWidth), 'Settings fit at 200% text size');
    await page.keyboard.press('Escape');
    await page.evaluate(() => document.documentElement.style.removeProperty('font-size'));
    await page.locator('.connection-panel').evaluate(el => el.open = true);
    await page.locator('#disconnect').click();
    assert.equal(await page.locator('#memory-count').textContent(), '0 of 20 notes');
    assert.equal(await page.locator('#memory-content').inputValue(), '');
    assert.equal(await page.evaluate(() => localStorage.length), 0);
    assert.deepEqual(errors, []);
    console.log('PASS: theme preview/apply/reload/failure/reset; communication save/live preview; reviewed memory CRUD; streaming/cancel; mobile overflow; Escape; disconnect cleanup.');
  } finally {
    await browser.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
